Chage log location
internetarchive/Zeno pull request #88
Opened 2024-07-23 05:20 UTC by nick2432

I updated the directory where log files are written from ./jobs/ to ./jobs/logs/. Previously, logs were being written directly to the /jobs directory, which was not the intended location. By changing the path to ./jobs/logs/, the logs will now be stored in the designated subdirectory, improving organization and making it easier to manage log files. This update helps ensure that logs are kept separate from other files in the /jobs directory, adhering to a cleaner and more logical directory structure.
![Screenshot from 2024-07-23 10-46-17](https://github.com/user-attachments/assets/5c2595e0-4078-4f80-9433-67542c040d0c)

2024-07-23 08:20 UTC, CorentinB commented
Thanks @nick2432! Problem is that with this way of adding the logs path, it doesn't respect --jobs.

2024-07-23 12:09 UTC, equals215 commented
> Thanks @nick2432! Problem is that with this way of adding the logs path, it doesn't respect --jobs.

@CorentinB did it ever? Wasn't aware of that

2024-07-23 12:20 UTC, CorentinB commented
> > Thanks @nick2432! Problem is that with this way of adding the logs path, it doesn't respect --jobs.
> 
> 
> 
> @CorentinB did it ever? Wasn't aware of that

Yes basically if --jobs isn't used, "logs", "warcs" etc are in the "jobs" directory, if --jobs is specified then it is put in the given directory's name, under "jobs". So "jobs/logs" becomes "jobs/whatever/logs".

2024-07-23 12:33 UTC, equals215 commented
> > > Thanks @nick2432! Problem is that with this way of adding the logs path, it doesn't respect --jobs.
> > 
> > 
> > @CorentinB did it ever? Wasn't aware of that
> 
> Yes basically if --jobs isn't used, "logs", "warcs" etc are in the "jobs" directory, if --jobs is specified then it is put in the given directory's name, under "jobs". So "jobs/logs" becomes "jobs/whatever/logs".

Heard, @nick2432 you will find the function `handleFlagsEdgeCases()` in `config/config.go`. This function is made to handle logic between flags at command runtime.
(and try to write a PR description yourself, this one looks **_very_** AI generated 😉)

2024-07-23 12:44 UTC, equals215 requested changes
> > > Thanks @nick2432! Problem is that with this way of adding the logs path, it doesn't respect --jobs.
> > 
> > 
> > @CorentinB did it ever? Wasn't aware of that
> 
> Yes basically if --jobs isn't used, "logs", "warcs" etc are in the "jobs" directory, if --jobs is specified then it is put in the given directory's name, under "jobs". So "jobs/logs" becomes "jobs/whatever/logs".

You will find the function `handleFlagsEdgeCases()` in `config/config.go`. This function is made to handle logic between flags at command runtime.
(and try to write a PR description yourself, this one looks **_very_** AI generated 😉)

2024-07-29 22:42 UTC, CorentinB commented
Hi @nick2432, do you know when the PR will be finished? Let us know if you need any help.

2024-08-04 13:53 UTC, nick2432 commented
> Hi @nick2432, do you know when the PR will be finished? Let us know if you need any help.

ya I will start working today 
I had an interview, so I was giving that

2024-08-04 13:59 UTC, nick2432 commented
> Hi @nick2432, do you know when the PR will be finished? Let us know if you need any help.

I will take 2-3 days

2024-08-05 19:12 UTC, CorentinB commented
Hi @nick2432, sorry but it took really too long. I implemented the necessary changes myself: https://github.com/internetarchive/Zeno/commit/6ab2d19552eebeba8ea591a11e8df74a1027b70f

2024-08-05 19:12 UTC, closed without merging